CREATE TABLE VENDOR_CHECK
(
	VENDOR_CHECK_ID NUMBER(16) NOT NULL PRIMARY KEY,
	DECIMAL_DIGIT NUMBER(5, 3) NOT NULL,
	INTEGER_NON_DIGIT NUMBER(5, 0) NOT NULL,
	LARGE_CHARACTER CLOB,
	TYPE_OF_CHAR CHAR(3),
	TYPE_OF_NCHAR NCHAR(3),
	TYPE_OF_VARCHAR2 VARCHAR2(32),
	TYPE_OF_VARCHAR2_MAX VARCHAR2(4000),
	TYPE_OF_NVARCHAR2 NVARCHAR2(32),
	TYPE_OF_CLOB CLOB,
	TYPE_OF_NCLOB NCLOB,
	TYPE_OF_DATE DATE,
	TYPE_OF_TIMESTAMP TIMESTAMP,
	TYPE_OF_BLOB BLOB,
	TYPE_OF_RAW RAW(512),
	TYPE_OF_BFILE BFILE
)  ;

CREATE TABLE VENDOR_LARGE_NAME_901234567890
(
	VENDOR_LARGE_NAME_901234567_ID NUMBER(16) NOT NULL PRIMARY KEY,
	VENDOR_LARGE_NAME_9012345_NAME VARCHAR(32) NOT NULL
)  ;

CREATE TABLE VENDOR_LARGE_NAME_90123456_REF
(
	VENDOR_LARGE_NAME_90123_REF_ID NUMBER(16) NOT NULL PRIMARY KEY,
	VENDOR_LARGE_NAME_901_REF_NAME VARCHAR(32) NOT NULL,
	VENDOR_LARGE_NAME_901234567_ID NUMBER(16)
)  ;

ALTER TABLE VENDOR_LARGE_NAME_90123456_REF ADD CONSTRAINT FK_VENDOR_LARGE_NAME_$$$_REF 
	FOREIGN KEY (VENDOR_LARGE_NAME_901234567_ID) REFERENCES VENDOR_LARGE_NAME_901234567890 (VENDOR_LARGE_NAME_901234567_ID) ;

CREATE TABLE VENDOR_EXCEPT
(
	VENDOR_EXCEPT_ID NUMBER(16) NOT NULL PRIMARY KEY,
	VANDOR_EXCEPT_NAME VARCHAR2(256)
)  ;

CREATE TABLE VENDOR_REF_EXCEPT
(
	VENDOR_REF_EXCEPT_ID NUMBER(16) NOT NULL PRIMARY KEY,
	VENDOR_EXCEPT_ID NUMBER(16) NOT NULL
)  ;

CREATE TABLE VENDOR_TARGET
(
	VENDOR_TARGET_ID NUMBER(16) NOT NULL PRIMARY KEY,
	VANDOR_TARGET_NAME VARCHAR2(256)
)  ;

CREATE TABLE VENDOR_REF_TARGET
(
	VENDOR_REF_TARGET_ID NUMBER(16) NOT NULL PRIMARY KEY,
	VENDOR_TARGET_ID NUMBER(16) NOT NULL
)  ;

ALTER TABLE VENDOR_REF_EXCEPT ADD CONSTRAINT FK_VENDOR_REF_EXCEPT
	FOREIGN KEY (VENDOR_EXCEPT_ID) REFERENCES VENDOR_EXCEPT (VENDOR_EXCEPT_ID) ;
	
ALTER TABLE VENDOR_REF_TARGET ADD CONSTRAINT FK_VENDOR_REF_TARGET
	FOREIGN KEY (VENDOR_TARGET_ID) REFERENCES VENDOR_TARGET (VENDOR_TARGET_ID) ;


-- Two synonyms for the problem 'Duplicate Column of Synonym' at 2009/02/21
-- It's a strange behavior of Oracle JDBC driver.
-- DatabaseMetaData.getColumns() returns Table's with Synonym's.
CREATE SYNONYM VENDOR_SYNONYM_MEMBER FOR MEMBER;
CREATE SYNONYM MEMBER_VENDOR_SYNONYM FOR MEMBER;

CREATE SYNONYM VD_SYNONYM_MEMBER FOR MEMBER;
CREATE SYNONYM VD_SYNONYM_MEMBER_LOGIN FOR MEMBER_LOGIN;
CREATE SYNONYM VD_SYNONYM_MEMBER_WITHDRAWAL FOR MEMBER_WITHDRAWAL;
CREATE SYNONYM VD_SYNONYM_PRODUCT FOR PRODUCT;
CREATE SYNONYM VD_SYNONYM_PRODUCT_STATUS FOR PRODUCT_STATUS;
CREATE SYNONYM VD_SYNONYM_VENDOR_EXCEPT FOR VENDOR_EXCEPT;
CREATE SYNONYM VD_SYNONYM_VENDOR_REF_EXCEPT FOR VENDOR_REF_EXCEPT;
CREATE SYNONYM VD_SYNONYM_VENDOR_TARGET FOR VENDOR_TARGET;
CREATE SYNONYM VD_SYNONYM_VENDOR_REF_TARGET FOR VENDOR_REF_TARGET;

