
CREATE TABLE VENDOR_CHECK
(
	VENDOR_CHECK_ID NUMERIC(16) NOT NULL PRIMARY KEY,
	TYPE_OF_BOOLEAN BOOLEAN NOT NULL,
	TYPE_OF_INTEGER INTEGER,
	TYPE_OF_BIGINT BIGINT,
	TYPE_OF_FLOAT FLOAT,
	TYPE_OF_DOUBLE DOUBLE,
	TYPE_OF_DECIMAL_DECIMAL DECIMAL(5, 3),
	TYPE_OF_DECIMAL_INTEGER DECIMAL(5, 0),
	TYPE_OF_DECIMAL_BIGINT DECIMAL(12, 0),
	TYPE_OF_NUMERIC_DECIMAL NUMERIC(5, 3),
	TYPE_OF_NUMERIC_INTEGER NUMERIC(5, 0),
	TYPE_OF_NUMERIC_BIGINT NUMERIC(12, 0),
	TYPE_OF_TEXT TEXT,
	TYPE_OF_TINYTEXT TINYTEXT,
	TYPE_OF_MEDIUMTEXT MEDIUMTEXT,
	TYPE_OF_LONGTEXT LONGTEXT,
	TYPE_OF_DATE DATE,
	TYPE_OF_DATETIME DATETIME,
	TYPE_OF_TIMESTAMP TIMESTAMP,
	TYPE_OF_TIME TIME,
	TYPE_OF_YEAR YEAR,
	TYPE_OF_BLOB BLOB(2000),
	TYPE_OF_TINYBLOB TINYBLOB,
	TYPE_OF_MEDIUMBLOB MEDIUMBLOB,
	TYPE_OF_LONGBLOB LONGBLOB,
	TYPE_OF_BINARY BINARY,
	TYPE_OF_VARBINARY VARBINARY(1000),
	TYPE_OF_ENUM ENUM('red','blue','yellow'),
	TYPE_OF_SET SET('red','blue','yellow')
)  ;

CREATE TABLE VENDOR_TOKEN
(
	VENDOR_TOKEN_ID NUMERIC(16) NOT NULL PRIMARY KEY,
	TOKEN_NUMBER INTEGER,
	TOKEN_NAME VARCHAR(200)
)  ;

CREATE TABLE VENDOR_SELF_REFERENCE
(
	SELF_REFERENCE_ID NUMERIC(16) NOT NULL PRIMARY KEY,
	SELF_REFERENCE_NAME VARCHAR(200) NOT NULL,
	PARENT_ID NUMERIC(16)
)  ;

ALTER TABLE VENDOR_SELF_REFERENCE ADD CONSTRAINT FK_VENDOR_SELF_REFERENCE_PARENT
	FOREIGN KEY (PARENT_ID) REFERENCES VENDOR_SELF_REFERENCE (SELF_REFERENCE_ID) ;

-- 'MYSELF_CHECK' and 'MYSELF' for MyselfInScopeSubQuery Check
CREATE TABLE MYSELF_CHECK ( 
	MYSELF_CHECK_ID integer NOT NULL PRIMARY KEY,
	MYSELF_CHECK_NAME varchar(80) NOT NULL,
	MYSELF_ID integer
) ;
CREATE TABLE MYSELF (
	MYSELF_ID integer NOT NULL PRIMARY KEY,
	MYSELF_NAME varchar(80) NOT NULL
) ;
ALTER TABLE MYSELF_CHECK ADD CONSTRAINT FK_MYSELF_CHECK_SELF
	FOREIGN KEY (MYSELF_ID) REFERENCES MYSELF (MYSELF_ID) ;
